/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dk.alexander.javaAsyncPubsub;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Subject subject = new SampleSubject();

        new Thread(() -> {
            Scanner scanner = new Scanner(System.in);
            System.out.print("Enter message: ");
            while(scanner.hasNextLine()) {
                String input = scanner.nextLine();
                subject.publish(input);
                System.out.print("Enter message: ");
            }
        }).start();

        new Thread(() -> {
            subject.subscribe(new Observer() {
                @Override
                public void notify(Object payload) {
                    System.out.println("Message recieved: " + payload);
                }
            });
        }).start();
    }
}
